---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app.kubernetes.io/instance: microservice
    app.kubernetes.io/name: microservice
  name: ingress-tls
  namespace: microservice
spec:
  provider: azure
  secretObjects:
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data:
      - objectName: certificate
        key: tls.key
      - objectName: certificate
        key: tls.crt
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ~
    keyvaultName: ~
    objects: |
      array:
        - |
          objectName: certificate
          objectType: secret
    tenantId: ~
