---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  labels:
    app.kubernetes.io/instance: microservice
    app.kubernetes.io/name: microservice
  name: microservice
spec:
  provider: azure
  secretObjects:
    - secretName: microservice-secret
      type: Opaque
      data:
        - objectName: example-password
          key: EXAMPLE_PASSWORD
    - secretName: docker-registry
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: docker-config-json
          key: .dockerconfigjson
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ~
    keyvaultName: ~
    objects: |
      array:
        - |
          objectName: example-password
          objectType: secret
        - |
          objectName: docker-config-json
          objectType: secret
    tenantId: ~
