---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: microservice
    app.kubernetes.io/name: microservice
  name: microservice
automountServiceAccountToken: false
