---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: microservice
    app.kubernetes.io/name: microservice
  name: microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: microservice
    app.kubernetes.io/name: microservice
