---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:imjoseangel/microservices-template.git'
    path: minikube
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: microservice
